services:
  postgres:
    image: postgres:12.20
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task_db
    restart: unless-stopped
  redis:
    image: redis:7.0.12
    ports:
      - "6379:6379"
